### ISSUE TITLE
3.12.0 issue: TypeError: ws_connect() got an unexpected keyword argument 'cookies'

### ISSUE THREAD

**Issue by bachya** [miguelgrinberg/python-engineio#166]
I recently upgraded `python-socketio` to 4.5.0 and my app continued to work. When I upgraded `python-engineio` to 3.12.0, I start seeing this traceback:

```txt
Traceback (most recent call last):
  File "examples/test_websocket.py", line 44, in main
    await client.websocket.connect()
  File "/Users/abach/Git/aioambient/.venv/lib/python3.7/site-packages/aioambient/websocket.py", line 76, in connect
    transports=["websocket"],
  File "/Users/abach/Git/aioambient/.venv/lib/python3.7/site-packages/socketio/asyncio_client.py", line 111, in connect
    engineio_path=socketio_path)
  File "/Users/abach/Git/aioambient/.venv/lib/python3.7/site-packages/engineio/asyncio_client.py", line 77, in connect
    url, headers, engineio_path)
  File "/Users/abach/Git/aioambient/.venv/lib/python3.7/site-packages/engineio/asyncio_client.py", line 267, in _connect_websocket
    headers=headers, cookies=cookies)
TypeError: ws_connect() got an unexpected keyword argument 'cookies'
```

Let me know what further info I can provide.

**Comment by miguelgrinberg** [comment]
The fix is now in master, please give it a try.

**Comment by bachya** [comment]
Confirmed that 3.12.1 fixes it. 👍
