### ISSUE TITLE
v3.12+ does not appear to work in python2.7

### ISSUE THREAD

**Issue by jdrobbins** [miguelgrinberg/python-engineio#171]
I am getting an error on: 

`AttributeError: 'module' object has no attribute 'main_thread'`

It looks like it was introduced by this change: https://github.com/miguelgrinberg/python-engineio/commit/e1ed079a8dafe2b9ca596fa2fc2885a91d1b486d

Checking the python2.7 API does not show a `main_thread()` method in the threading module.

**Comment by miguelgrinberg** [comment]
I do not to maintain 2.7 compatibility anymore. I have stopped building that platform a while ago, so this is why 3.x constructs are going to start creeping in more and more.
